apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: smarthotelbackend 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smarthotelbackend 
    spec:
      containers:
        - name: smarthotelbackend 
          image: sh360acr.azurecr.io/smarthotelbackend 
          ports:
          - containerPort: 80