apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: discounts 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: discounts 
    spec:
      containers:
        - name: discounts 
          image: sh360acr.azurecr.io/discounts 
          ports:
          - containerPort: 80