apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: smarthoteldiscount 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smarthoteldiscount 
    spec:
      containers:
        - name: smarthoteldiscount 
          image: sh360acr.azurecr.io/smarthoteldiscount 
          ports:
          - containerPort: 80