apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: hsachinrajsmarthotelbackend 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hsachinrajsmarthotelbackend 
    spec:
      containers:
        - name: hsachinrajsmarthotelbackend 
          image: sh360acr.azurecr.io/hsachinrajsmarthotelbackend 
          ports:
          - containerPort: 80