apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: reviews 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews 
    spec:
      containers:
        - name: reviews 
          image: sh360acr.azurecr.io/smarthotel/reviews 
          ports:
          - containerPort: 80
